# Generated by Django 2.2.8 on 2019-12-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Імʼя')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Призвище')),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Електронна адреса')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Питання')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Категорія послуг')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=64, verbose_name='Імʼя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Призвище')),
                ('email', models.EmailField(max_length=128, verbose_name='Електронна почта')),
                ('phone_number', models.CharField(max_length=64, verbose_name='Номер телефона')),
            ],
        ),
    ]
