# Generated by Django 2.2.8 on 2019-12-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191230_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='service',
        ),
    ]
