# Generated by Django 2.2.8 on 2020-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200105_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='listservice',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Коментар'),
        ),
    ]
