# Generated by Django 2.2.8 on 2020-01-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200106_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Вартість'),
        ),
    ]
